version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "3003:3003"
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=mydb-dev
      - DB_USER=vinhle
      - DB_PASS=password
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:3003"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=mydb-dev
      - POSTGRES_USER=vinhle
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db: